use std::fs::File;
use std::io::{Read, Write};
use std::path::Path;
use std::env;

fn main() {
    println!("cargo:rerun-if-changed=../../include/lox.h");

    let lox_h_path = Path::new("../../include/lox.h");
    let mut file = File::open(lox_h_path).expect("Unable to open lox.h");
    let mut content = String::new();
    file.read_to_string(&mut content).expect("Unable to read lox.h");

    // Parse LoxValueType enum
    let enum_start = content.find("typedef enum {").expect("Cannot find LoxValueType enum start");
    let enum_end = content[enum_start..].find("} LoxValueType;").expect("Cannot find LoxValueType enum end") + enum_start;
    let enum_body = &content[enum_start + "typedef enum {".len()..enum_end];
    let mut enum_variants = Vec::new();
    for line in enum_body.lines() {
        let trimmed = line.trim().trim_end_matches(',');
        if !trimmed.is_empty() {
            enum_variants.push(trimmed.to_string());
        }
    }

    let mut rust_code = String::new();
    rust_code.push_str("// Generated by build.rs. Do not edit.\n\n");
    
    rust_code.push_str("#[allow(non_camel_case_types)]\n");
    rust_code.push_str("#[repr(C)]\n");
    rust_code.push_str("#[derive(Debug, Copy, Clone, PartialEq, Eq)]\n");
    rust_code.push_str("pub enum LoxValueType {\n");
    for var in &enum_variants {
        rust_code.push_str(&format!("    {},\n", var));
    }
    rust_code.push_str("}\n\n");

    // Emit union and structs that map to lox.h
    rust_code.push_str("
#[repr(C)]
#[derive(Copy, Clone)]
pub union LoxFfiValueUnion {
    pub boolean: bool,
    pub number: f64,
    pub string: *const std::ffi::c_char,
    pub array: *mut LoxFfiArray,
    pub buffer: *mut LoxFfiBuffer,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct LoxFfiValue {
    pub type_: LoxValueType,
    pub as_: LoxFfiValueUnion,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct LoxFfiArray {
    pub elements: *mut LoxFfiValue,
    pub length: std::ffi::c_int,
    pub capacity: std::ffi::c_int,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct LoxFfiBuffer {
    pub bytes: *mut std::ffi::c_uchar,
    pub size: std::ffi::c_int,
    pub capacity: std::ffi::c_int,
}

pub type LoxNativeFn = extern \"C\" fn(arg_count: std::ffi::c_int, args: *const LoxFfiValue) -> LoxFfiValue;

#[repr(C)]
pub struct LoxFfiApi {
    pub define_function: extern \"C\" fn(name: *const std::ffi::c_char, arity: std::ffi::c_int, fn_: LoxNativeFn),
    pub define_global: extern \"C\" fn(name: *const std::ffi::c_char, value: LoxFfiValue),
    pub make_nil: extern \"C\" fn() -> LoxFfiValue,
    pub make_bool: extern \"C\" fn(b: bool) -> LoxFfiValue,
    pub make_number: extern \"C\" fn(d: f64) -> LoxFfiValue,
    pub make_string: extern \"C\" fn(s: *const std::ffi::c_char) -> LoxFfiValue,
    pub make_array: extern \"C\" fn(length: std::ffi::c_int, elements: *const LoxFfiValue) -> LoxFfiValue,
    pub make_buffer: extern \"C\" fn(size: std::ffi::c_int, bytes: *const std::ffi::c_uchar) -> LoxFfiValue,
    pub set_error: extern \"C\" fn(message: *const std::ffi::c_char),
    pub define_function_with_help: extern \"C\" fn(name: *const std::ffi::c_char, arity: std::ffi::c_int, fn_: LoxNativeFn, help: *const std::ffi::c_char),
}
");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("bindings.rs");
    let mut f = File::create(&dest_path).expect("Could not create bindings.rs");
    f.write_all(rust_code.as_bytes()).expect("Could not write bindings.rs");
}
